### PR TITLE
API Endpoint - FleshedAPI into Develop

### PR DESCRIPTION
**Pull request by AdamSlack**
Implemented an API Endpoint to allow the fetching of apps and app data from the database

Params include:
```
isFull: bool
title: string
developer: string
genre: string
appId: string
```

future updates need to include: ```permission: string, package: string, hosts: string```

Example URL:
``` /api/apps/?isFull=false/developer=Zynga ```

The above when used with Curl might return a json object similar to:
```
[
     {
          "Title":"Frozen Free Fall",
          "App":"com.disney.frozensaga_goo"
     },
     {
          "Title":"Candy Crush Jelly Saga",
          "App":"com.king.candycrushjellysaga"
     },
     {
          "Title":"Word Search",
          "App":"com.asgardsoft.words"
     }
]
```

```TODO: Move some of this to a README.md```

### CODE REVIEW

**Comment by deanott** [comment]
Why is this not in a README right now?

**Comment by AdamSlack** [comment]
@deanott Please review the FormParam method.
```
main.go:148: github.com/sociam/xray-archiver/pipeline/db.FormParam composite literal uses unkeyed fields
```

**Comment by deanott** [comment]
This is all runs okay, beside the developer id returning as 0... that should really be the correct id in the developer table.

**Comment by deanott** [comment]
@sauyon what to check this out and see if your happy? if your not happy you should comment why

**Comment by deanott** [comment]
@sauyon @AdamSlack need someone to merge this in

**Comment by AdamSlack** [comment]
@deanott we're waiting on you to add a review...

**Pull request merged**
